draw_self()
draw_set_halign(fa_center)
draw_set_valign(fa_middle)
draw_set_color((image_index=1 ? c_yellow : c_white))
draw_text_scribble(x+62,y+46,GetString("str_game_selection_quit"))
draw_set_color(c_white)