Anim_Uninit();
Dialog_Uninit();
Flag_Uninit();
Encounter_Uninit();
Input_Uninit();
Demo_Uninit();
Shop_Uninit();
file_delete("console.txt");
if(file_exists(working_directory+"/file10.ini")){file_delete(working_directory+"/file10.ini")}
if(directory_exists(working_directory+"/flag/10")){directory_destroy(working_directory+"/flag/10")}
#region Release Keys
keyboard_key_release(vk_up)
keyboard_key_release(vk_down)
keyboard_key_release(vk_left)
keyboard_key_release(vk_right)
keyboard_key_release(ord("W"))
keyboard_key_release(ord("S"))
keyboard_key_release(ord("A"))
keyboard_key_release(ord("D"))
keyboard_key_release(vk_enter)
keyboard_key_release(vk_shift)
keyboard_key_release(vk_control)
keyboard_key_release(vk_space)
keyboard_key_release(vk_f2)
keyboard_key_release(vk_escape)
#endregion
#region Music
audio_destroy_stream(bgm_bird)
audio_destroy_stream(bgm_gameover)
audio_destroy_stream(bgm_heartbeat)
audio_destroy_stream(bgm_menu_spring_autumn)
audio_destroy_stream(bgm_menu_summer)
audio_destroy_stream(bgm_menu_winter)
audio_destroy_stream(bgm_rickroll)
audio_destroy_stream(bgm_sansdate)
audio_destroy_stream(bgm_shop)
audio_destroy_stream(bgm_snowdin)
audio_destroy_stream(bgm_thinking)
audio_destroy_stream(loop_rain)
#endregion