Battle_SetTurnInfo(BATTLE_TURN.TIME,-1)
Battle_SetTurnInfo(BATTLE_TURN.BOARD_UP,64)
Battle_SetTurnInfo(BATTLE_TURN.BOARD_DOWN,64)
Battle_SetTurnInfo(BATTLE_TURN.BOARD_LEFT,64)
Battle_SetTurnInfo(BATTLE_TURN.BOARD_RIGHT,64)
timer=0
bgm=audio_play_sound(bgm_haike,0,0)
audio=0

bgu=instance_create_depth(0,0-24,DEPTH_BATTLE.BG,battle_bg)
bgu.image_yscale=2.5
bgu.tempscale=2.5
bgu.image_blend=c_white
bgu.alarm[2]=1
bgd=instance_create_depth(640,480+24,DEPTH_BATTLE.BG,battle_bg)
bgd.image_angle=180
bgd.image_yscale=2.5
bgd.tempscale=2.5
bgd.image_blend=c_white
bgd.alarm[2]=1
bgl=instance_create_depth(0-24,480,DEPTH_BATTLE.BG,battle_bg)
bgl.image_angle=90
bgl.image_yscale=2.5
bgl.tempscale=2.5
bgl.image_blend=c_white
bgl.alarm[2]=1
bgr=instance_create_depth(640+24,0,DEPTH_BATTLE.BG,battle_bg)
bgr.image_angle=-90
bgr.image_yscale=2.5
bgr.tempscale=2.5
bgr.image_blend=c_white
bgr.alarm[2]=1

platform=noone
bstemp=false
bsangle=0
bsmax=45
board=noone